default_platform(:android)

platform :android do

  desc "Run unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build signed release AAB"
  lane :internal do
    gradle(task: "bundleRelease")
  end

end