default_platform(:android)

platform :android do

  desc "Run unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build signed release AAB"
  lane :internal do
    gradle(task: "assembleRelease")

    firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    service_credentials_file: ENV["GOOGLE_APPLICATION_CREDENTIALS"],
    android_artifact_type: "APK",
    android_artifact_path: "app/build/outputs/apk/release/app-release.apk",
    release_notes: "Automated CI build"
    )
  end

end